---
title: "Viz_and_eda"
author: "Priyal"
date: "9/27/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```



```{r}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Start  a plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Plot focussing just on Central Park data
```{r}
weather_df %>% 
  filter(name =="CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```


##More plot options

Add an aesthetic

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

Add a geom

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name, alpha = 0.4)) +
  geom_smooth(se = FALSE)
```

Add some options...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE)
```

Facetting..

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) +
  geom_smooth(se = FALSE)+
  facet_grid( ~ name)
```

A more interesting plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point() +
  geom_smooth(se = FALSE) + 
  facet_grid( ~ name)

```

LA
```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
```

vs 

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue"))
```

## Univariate plot

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram() + 
  facet_grid(~ name)
```

Density plot
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_density(alpha = .5) 
```

Box plot

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_boxplot()
```

Violin plot

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin()
```

```{r}
ggplot(weather_df,aes(x = tmax, y = name)) + 
geom_density_ridges(scale = .85)
```


```{r}
weather_plot = ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) 

ggsave("weather_plot.pdf", weather_plot, width = 8, height = 5)
```

```{r}
ggplot(weather_df, aes(x = prcp)) + 
  geom_density(aes(fill = name), alpha = .5) 
```

```{r}
ggplot(weather_df, aes(y = prcp, x = name)) + 
  geom_boxplot() 
```

```{r}
ggplot(weather_df, aes(y = prcp, x = name)) + 
  geom_violin() 
```

```{r}
weather_df %>% 
  filter(prcp > 0) %>% 
  ggplot(aes(x = prcp, y = name)) + 
  geom_density(scale = .85)
```

